local_balenaos:
  app-name: local-app
  build-triggers:
    - Dockerfile: 7915a4727f6d380f9a7c925833255aa0343e2d06bcea74ce36044baa6fde8090
  environment: []
destination: /usr/src/app
ignore:
  - .git
  - node_modules/
